kotlin.code.style=official
kotlin.incremental.useClasspathSnapshot=true
kotlin.jvm.target.validation.mode=ERROR

# Kotlin Multiplatform settings
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.binary.memoryModel=experimental
kotlin.native.enableDependencyPropagation=false
kotlin.native.cacheKind=none
