[versions]
clikt = "5.0.3"
docker = "9.4.0"
gcsm = "2.74.0"
http4k = "6.18.0.1"
junit5 = "5.13.4"
kotlin = "2.2.20"
mordant = "3.0.2"
plugin-shadow = "9.1.0"
plugin-versionsUpdate = "1.0.0"
serialization-json = "1.9.0"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
clikt-markdown = { module = "com.github.ajalt.clikt:clikt-markdown", version.ref = "clikt" }
google-cloud-secretmanager = { module = "com.google.cloud:google-cloud-secretmanager", version.ref = "gcsm" }
http4k-client-okhttp = { module = "org.http4k:http4k-client-okhttp", version.ref = "http4k" }
http4k-core = { module = "org.http4k:http4k-core", version.ref = "http4k" }
http4k-server-netty = { module = "org.http4k:http4k-server-netty", version.ref = "http4k" }
http4k-template-handlebars = { module = "org.http4k:http4k-template-handlebars", version.ref = "http4k" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }

[plugins]
docker = { id = "com.bmuschko.docker-java-application", version.ref = "docker" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "plugin-shadow" }
versions-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "plugin-versionsUpdate" }
